### ISSUE TITLE
make test errors on mac os x lion

### ISSUE THREAD

**Issue by zrbecker** [Wallbraker/DCPU-TCC#1]
I attempted to use the linux instructions on mac os x, which sometimes work. ./configue and make worked fine, but make test fails with the following error.

make -C tests test
gcc -o libtcc_test libtcc_test.c ../libtcc.a -I.. -Wall -g -O2 -fno-strict-aliasing -Wno-pointer-sign -Wno-sign-compare -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -m64 -Wl,-flat_namespace,-undefined,warning -lm -ldl 
------------ libtest ------------
./libtcc_test lib_path=..
Hello World!
fib(32) = 2178309
add(32, 64) = 96
cp ../include/tcclib.h .
gcc -o tcctest.gcc tcctest.c -I. -w -Wall -g -O2 -fno-strict-aliasing -Wno-pointer-sign -Wno-sign-compare -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -m64 -Wl,-flat_namespace,-undefined,warning -std=gnu99
./tcctest.gcc > test.ref
------------ test1 ------------
../tcc -B.. -run tcctest.c > test.out1
tcctest.c:2060: warning: assignment makes pointer from integer without a cast
tcctest.c:2065: warning: assignment makes pointer from integer without a cast
tcc: error: undefined symbol 'weak_f1'
tcc: error: undefined symbol 'weak_v1'
tcc: error: undefined symbol 'weak_fpa'
tcc: error: undefined symbol 'weak_fpb'
tcc: error: undefined symbol 'weak_fpc'
make[1]: **\* [test1] Error 255
make: **\* [test] Error 2

**Comment by Wallbraker** [comment]
So you can build the project or is this blocking you from getting dcpu-tcc up and running?

This is a general issue with TCC.

Cheers, Jakob.
